### ISSUE TITLE
The cmake is not corrected

### ISSUE THREAD

**Issue by cychitivav** [fegonzalez7/rob_unal_clase4#2]
I did all the steps in the guide and the messages from dynamixel seem to be fine
![image](https://user-images.githubusercontent.com/30636259/164942962-994cdcce-c473-494c-bff9-047359f7eb58.png)

I know that the cmake part is an issue but I still checked it and the following appears
![image](https://user-images.githubusercontent.com/30636259/164943002-94c2fdc9-5b75-48ef-8e36-0a4114b77444.png)

I already did the export part and cmake still doesn't work , so I wonder if the cmake configuration is necessary, if the messages in MATLAB already work for me?

**Comment by fegonzalez7** [comment]
Let's see if you can connect to the dynamixel bridge next class.

Have you checked if the paths are the same for you or if the files actually? exists?

export LD_PRELOAD="/usr/lib/x86_64-linux-gnu/libstdc++.so.6"
export LD_PRELOAD="/usr/lib/x86_64-linux-gnu/libstdc++.so.6:/usr/lib/x86_64-linux-gnu/libcurl.so"

**Comment by cychitivav** [comment]
The files do exist but when I add the lines to the .bashrc, restart matlab and run `!cmake --version`, I get the same error. I don't know if it has something to do with it but when running `getenv('LD_LIBRARY_PATH')`, I get a list and the files that are written in the .bashrc do not appear

![image](https://user-images.githubusercontent.com/30636259/165021315-062ab9aa-a21a-4353-a99d-351a4f9ea9a8.png)

**Comment by felipeg17** [comment]
I think the issue has to do with the way Matlab is being launched. If you edit the bash and launch it through it, the problem does not happen.
